### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Sunner4nwpu** [chi0tzp/PyVGGFace#1]
Hello, I download the pretrained file vgg_face_torch.tar.gz (Torch), and follow your step1 but I got the error "unhashable type: 'numpy.ndarray'", could you help me with this error, or may you share your converted .pth model? Thanks a lot

**Comment by chi0tzp** [comment]
Hi @Sunner4nwpu, thanks for your comment. Please check if it works for you now. I have provided a `requirements.txt` for building a virtual environment, as shown in the readme file. Please try to follow these guideline and let me know if it works for you.

**Comment by Sunner4nwpu** [comment]
Thank you very much!!! It works for me now
