### ISSUE TITLE
why substract np.array([129.1863, 104.7624, 93.5940] with the input image

### ISSUE THREAD

**Issue by rrryan2016** [chi0tzp/PyVGGFace#2]
As describe in the title, I get confused about the process here 

https://github.com/chi0tzp/PyVGGFace/blob/1a56feebf06d8b3b3001c79b181c5a09a59ed228/demo.py#L36

Is this process exactly the 

>  ‘with the average face image (computed from the training set) subtracted’ 

in _Deep Face Recognition_

**Comment by vinayak015** [comment]
Hi @rrryan2016, I hope you have found the answer to that but in case if anyone is still looking then:

In paper they have mentioned input is subtracted by the average face, and I assume that's the average face subtraction going on.


<img width="1376" alt="Screenshot 2022-02-10 at 11 03 23 AM" src="https://user-images.githubusercontent.com/13629918/153384454-46e0982c-26ba-4584-a3b9-3d3fb1254bba.png">
